### ISSUE TITLE
是否可以支持post 中显示 custom post type的文章呢

### ISSUE THREAD

**Issue by skating507** [chaozh/Post-Series#1]
如标题，看到好像只支持默认的文章，不可以在默认文章里面显示自定义文章。

**Comment by chaozh** [comment]
目前仅支持post和page类型，这个可以考虑实现一下

**Comment by chaozh** [comment]
已经简单实现支持，未来可以实现配置化，比如设置某些自定义类型支持专题系统，某些不支持

**Comment by chaozh** [comment]
已经简单实现支持，未来可以实现配置化，比如设置某些自定义类型支持专题系统，某些不支持
